apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
 name: httpbin-api
spec:
 name: httpbin
 protocol: http
 active: true
 proxy:
   target_url: http://httpbin
   listen_path: /httpbin
   strip_listen_path: true