apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: not-important
spec:
  use_keyless: false
  use_standard_auth: true
  auth_configs:
    authToken:
      auth_header_name: Authorization
  enable_ip_whitelisting: true
  allowed_ips:
    - 127.0.0.1