apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: staging
patches:
  - patch: |-
      apiVersion: tyk.tyk.io/v1alpha1
      kind: ApiDefinition
      metadata:
        name: httpbin-api
      spec:
        tags:
          - staging
          - httpbin
        detailed_tracing: true
        use_keyless: false
        enable_jwt: true
        strip_auth_data: false
        jwt_signing_method: rsa
        jwt_source: aHR0cDovL2tleWNsb2FrLmtleWNsb2FrL3JlYWxtcy9qd3Qtc3RhZ2luZy9wcm90b2NvbC9vcGVuaWQtY29ubmVjdC9jZXJ0cw==
        jwt_identity_base_field: sub
        jwt_policy_field_name: pol
        jwt_default_policies:
          - staging/jwt-policy
        proxy:
          target_url: http://httpbin.staging.svc