apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: httpbin-staging
replicas:
- name: httpbin
  count: 1
patches:
- path: api_auth.yaml
  target:
    kind: ApiDefinition
    labelSelector: app=httpbin
- path: api_config.yaml
  target:
    kind: ApiDefinition
    labelSelector: app=httpbin
- patch: |-
    apiVersion: tyk.tyk.io/v1alpha1
    kind: ApiDefinition
    metadata:
      name: httpbin-api
      namespace: httpbin
    spec:
      proxy:
        target_url: http://httpbin.httpbin-staging.svc