apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: staging
patches:
- patch: |-
    apiVersion: tyk.tyk.io/v1alpha1
    kind: ApiDefinition
    metadata:
      name: httpbin-api
    spec:
      tags:
        - staging
        - httpbin
      proxy:
        target_url: http://httpbin.staging.svc