apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-prod
spec:
  destination:
    namespace: httpbin
    server: https://kubernetes.default.svc
  source:
    path: apps/httpbin/overlays/prod
    repoURL: https://github.com/TykTechnologies/tyk-operator-demo
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
