apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies-prod
spec:
  destination:
    namespace: production
    server: 'https://kubernetes.default.svc'
  source:
    path: infrastructure/policies/prod
    repoURL: 'https://github.com/caroltyk/tyk-operator-demo'
  sources: []
  project: app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
