apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin-staging
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/httpbin/overlays/staging
    repoURL: 'https://github.com/caroltyk/tyk-operator-demo'
  sources: []
  project: app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
