apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies-staging
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: policies/staging
    repoURL: 'https://github.com/caroltyk/tyk-operator-demo'
  sources: []
  project: app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
